blank_issues_enabled: false
contact_links:
  - name: Ask a question or start a discussion
    url: https://github.com/darshan-rambhia/vamsa/discussions
    about: Please use GitHub Discussions for questions or general ideas.
